/* src/config_clp.h.  Generated by configure.  */
/* src/config_clp.h.in.  */

/* Define to 1, 2, 3, or 4 if Aboca should be build. */
/* #undef CLP_HAS_ABC */
#define CLP_HAS_ABC 1
/* Version number of project */
#define CLP_VERSION "1.16.11"

/* Major Version number of project */
#define CLP_VERSION_MAJOR 1

/* Minor Version number of project */
#define CLP_VERSION_MINOR 16

/* Release Version number of project */
#define CLP_VERSION_RELEASE 11
