/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_coinor_Bonmin */

#ifndef _Included_org_coinor_Bonmin
#define _Included_org_coinor_Bonmin
#ifdef __cplusplus
extern "C" {
#endif
#undef org_coinor_Bonmin_C_STYLE
#define org_coinor_Bonmin_C_STYLE 0L
#undef org_coinor_Bonmin_FORTRAN_STYLE
#define org_coinor_Bonmin_FORTRAN_STYLE 1L
#undef org_coinor_Bonmin_SOLVE_SUCCEEDED
#define org_coinor_Bonmin_SOLVE_SUCCEEDED 0L
#undef org_coinor_Bonmin_ACCEPTABLE_LEVEL
#define org_coinor_Bonmin_ACCEPTABLE_LEVEL 1L
#undef org_coinor_Bonmin_INFEASIBLE_PROBLEM
#define org_coinor_Bonmin_INFEASIBLE_PROBLEM 2L
#undef org_coinor_Bonmin_SEARCH_DIRECTION_TOO_SMALL
#define org_coinor_Bonmin_SEARCH_DIRECTION_TOO_SMALL 3L
#undef org_coinor_Bonmin_DIVERGING_ITERATES
#define org_coinor_Bonmin_DIVERGING_ITERATES 4L
#undef org_coinor_Bonmin_USER_REQUESTED_STOP
#define org_coinor_Bonmin_USER_REQUESTED_STOP 5L
#undef org_coinor_Bonmin_ITERATION_EXCEEDED
#define org_coinor_Bonmin_ITERATION_EXCEEDED -1L
#undef org_coinor_Bonmin_RESTORATION_FAILED
#define org_coinor_Bonmin_RESTORATION_FAILED -2L
#undef org_coinor_Bonmin_ERROR_IN_STEP_COMPUTATION
#define org_coinor_Bonmin_ERROR_IN_STEP_COMPUTATION -3L
#undef org_coinor_Bonmin_NOT_ENOUGH_DEGREES_OF_FRE
#define org_coinor_Bonmin_NOT_ENOUGH_DEGREES_OF_FRE -10L
#undef org_coinor_Bonmin_INVALID_PROBLEM_DEFINITION
#define org_coinor_Bonmin_INVALID_PROBLEM_DEFINITION -11L
#undef org_coinor_Bonmin_INVALID_OPTION
#define org_coinor_Bonmin_INVALID_OPTION -12L
#undef org_coinor_Bonmin_INVALID_NUMBER_DETECTED
#define org_coinor_Bonmin_INVALID_NUMBER_DETECTED -13L
#undef org_coinor_Bonmin_UNRECOVERABLE_EXCEPTION
#define org_coinor_Bonmin_UNRECOVERABLE_EXCEPTION -100L
#undef org_coinor_Bonmin_NON_IPOPT_EXCEPTION
#define org_coinor_Bonmin_NON_IPOPT_EXCEPTION -101L
#undef org_coinor_Bonmin_INSUFFICIENT_MEMORY
#define org_coinor_Bonmin_INSUFFICIENT_MEMORY -102L
#undef org_coinor_Bonmin_INTERNAL_ERROR
#define org_coinor_Bonmin_INTERNAL_ERROR -199L
/*
 * Class:     org_coinor_Bonmin
 * Method:    AddBonminIntOption
 * Signature: (JLjava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_coinor_Bonmin_AddBonminIntOption
  (JNIEnv *, jobject, jlong, jstring, jint);

/*
 * Class:     org_coinor_Bonmin
 * Method:    AddBonminNumOption
 * Signature: (JLjava/lang/String;D)Z
 */
JNIEXPORT jboolean JNICALL Java_org_coinor_Bonmin_AddBonminNumOption
  (JNIEnv *, jobject, jlong, jstring, jdouble);

/*
 * Class:     org_coinor_Bonmin
 * Method:    AddBonminStrOption
 * Signature: (JLjava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_coinor_Bonmin_AddBonminStrOption
  (JNIEnv *, jobject, jlong, jstring, jstring);

/*
 * Class:     org_coinor_Bonmin
 * Method:    CreateBonminProblem
 * Signature: (IIIII)J
 */
JNIEXPORT jlong JNICALL Java_org_coinor_Bonmin_CreateBonminProblem
  (JNIEnv *, jobject, jint, jint, jint, jint, jint);

/*
 * Class:     org_coinor_Bonmin
 * Method:    FreeBonminProblem
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_coinor_Bonmin_FreeBonminProblem
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_coinor_Bonmin
 * Method:    OptimizeTMINLP
 * Signature: (JLjava/lang/String;[D[D[D[D[D[D[D[D[D[I[I[I)I
 */
JNIEXPORT jint JNICALL Java_org_coinor_Bonmin_OptimizeTMINLP
  (JNIEnv *, jobject, jlong, jstring, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
